Add freeze_last_access_time/freeze_last_write_time for Windows
The Windows build started failing for Rust 1.94.0:
```
error[E0046]: not all trait items implemented, missing: `freeze_last_access_time`, `freeze_last_write_time`
  --> tokio\src\fs\open_options\mock_open_options.rs:12:1
   |
12 | / mock! {
13 | |     #[derive(Debug)]
14 | |     pub OpenOptions {
15 | |         pub fn append(&mut self, append: bool) -> &mut Self;
...  |
31 | |     #[cfg(windows)]
32 | |     impl OpenOptionsExt for OpenOptions {
   | |_______________________________________^ missing `freeze_last_access_time`, `freeze_last_write_time` in implementation
   |
   = note: this error originates in the macro `mock` (in Nightly builds, run with -Z macro-backtrace for more info)
   = help: implement the missing item: `fn freeze_last_access_time(&mut self, _: bool) -> &mut Self { todo!() }`
   = help: implement the missing item: `fn freeze_last_write_time(&mut self, _: bool) -> &mut Self { todo!() }`
```