Fix docs.rs build with cfg(docsrs)
For crates which set `rustc-args = ["--cfg", "docsrs"] ` in `[package.metadata.docs.rs]`, tokio-stream fails to build on docs.rs with

```
[INFO] [stderr]    Compiling tokio-stream v0.1.3
[INFO] [stderr] error[E0636]: the feature `doc_cfg` has already been declared
[INFO] [stderr]   --> /opt/rustwide/cargo-home/registry/src/github.com-1ecc6299db9ec823/tokio-stream-0.1.3/src/lib.rs:24:29
[INFO] [stderr]    |
[INFO] [stderr] 24 | #![cfg_attr(docsrs, feature(doc_cfg))]
[INFO] [stderr]    |                             ^^^^^^^
```

The first occurence of the same `cfg_attr` command is on https://github.com/tokio-rs/tokio/blob/master/tokio-stream/src/lib.rs#L17