tokio-macros: disambiguate name resolution for "tokio::runtime::Builder"
The previous version fails when another thing with the name "tokio" is
in scope, with a very unhelpful error message:

```
error[E0433]: failed to resolve: could not find `runtime` in `tokio`
  --> src/main.rs:11:1
   |
11 | #[::tokio::main]
   | ^^^^^^^^^^^^^^^^ not found in `tokio::runtime`
   |
   = note: this error originates in an attribute macro (in Nightly builds, run with -Z macro-backtrace for more info)
help: consider importing one of these items
   |
7  | use std::thread::Builder;
   |
7  | use tokio::runtime::Builder;
   |

error: aborting due to previous error
```

In the case I encountered, the problem arose because of a wildcard import like
`use foo::bar::*;` which happened to contain a `foo::bar::tokio` submodule.