tcp_into_std: assign an unused port
Assigning a specific port can lead to colisions and test failures
if this port is already in use. This results in this test failing
~0.5% of the time on Android's CI.

Fixes:
test tcp_into_std ... FAILED

failures:

---- tcp_into_std stdout ----
Error: Os { code: 98, kind: AddrInUse, message: "Address already in use" }