Bump required ahash version
Fixes this error:
   error[E0635]: unknown feature `stdsimd`
    --> /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ahash-0.8.4/src/lib.rs:99:42
     |
  99 | #![cfg_attr(feature = "stdsimd", feature(stdsimd))]
     |                                          ^^^^^^^

As of 0.8.7, ahash no longer tries to use stdsimd on nightly