Revert "sync: add `broadcast::Sender::closed`"
This reverts commit 5c8cd33820b029ebc8263c461fe03a2cc7f87577.

Reason for revert: Failing tests:

---- tokio/src/sync/broadcast.rs - sync::broadcast::Sender<T>::closed (line 819) stdout ----
Test executable failed (exit status: 101).

stderr:
thread 'main' panicked at tokio/src/sync/broadcast.rs:22:5:
assertion failed: tx.closed().now_or_never().is_some()
stack backtrace:
   0: rust_begin_unwind
             at /rustc/9fc6b43126469e3858e2fe86cafb4f0fd5068869/library/std/src/panicking.rs:665:5
   1: core::panicking::panic_fmt
             at /rustc/9fc6b43126469e3858e2fe86cafb4f0fd5068869/library/core/src/panicking.rs:76:14
   2: core::panicking::panic
             at /rustc/9fc6b43126469e3858e2fe86cafb4f0fd5068869/library/core/src/panicking.rs:148:5
   3: rust_out::main::{{closure}}
   4: tokio::runtime::park::CachedParkThread::block_on::{{closure}}
   5: tokio::runtime::park::CachedParkThread::block_on
   6: tokio::runtime::context::blocking::BlockingRegionGuard::block_on
   7: tokio::runtime::scheduler::multi_thread::MultiThread::block_on::{{closure}}
   8: tokio::runtime::context::runtime::enter_runtime
   9: tokio::runtime::scheduler::multi_thread::MultiThread::block_on
  10: tokio::runtime::runtime::Runtime::block_on_inner
  11: tokio::runtime::runtime::Runtime::block_on
  12: rust_out::main
  13: core::ops::function::FnOnce::call_once
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.